### ISSUE TITLE
issue with getting metadata

### ISSUE THREAD

**Issue by techie311** [jwueller/jellyfin-plugin-onepace#73] opened 2024-07-31 16:25 UTC
![image](https://github.com/user-attachments/assets/b4dd73b2-91ff-40e0-ba99-ba39a80d1418)
![image](https://github.com/user-attachments/assets/6b53702c-0684-4d16-b44e-e26ecd1b24c8)
so u can see my folder naming is correct i think if wrong let me know because i used the same name as downloaded file
and i have installed one pace plugin and its active
![image](https://github.com/user-attachments/assets/bfc5c4e9-c797-4017-ac1c-ee526c36aafb)
my jellyfin library settings
![image](https://github.com/user-attachments/assets/8ed8b191-12cd-4b6c-b90b-754b7739045b)
![image](https://github.com/user-attachments/assets/5ac1f015-9655-4cb5-8ae1-750843b06ae1)
![image](https://github.com/user-attachments/assets/9e267f33-9cf1-4456-ae4d-078880612625)
![image](https://github.com/user-attachments/assets/bdf0e823-5851-4675-ba55-cfdef4a14f0b)
![image](https://github.com/user-attachments/assets/f709bc1b-38a1-4b29-adc0-94dab799a402)

all 1st option is one pace

and my jellyfin version 
![image](https://github.com/user-attachments/assets/e06c79dc-acc4-4716-b0c3-6cbf5023c51b)

after all done and multiple library scans and multiple replace metadata
it gets it as one piece tv show and each season is showing folder name and each episode showing as just one piece 1 one piece 2 and so on its not getting the correct one pace metadata

is there a way to fix this or is it jellyfin version issue

**Comment by gusjdy** [comment] 2024-08-07 01:47
Same issue here. Might it have something to do with onepace webpage being down?

**Comment by 0bscenity** [comment] 2024-08-07 02:23
is this a duplicate of this? https://github.com/jwueller/jellyfin-plugin-onepace/issues/66

**Comment by 0bscenity** [comment] 2024-08-07 04:09
> Same issue here. Might it have something to do with onepace webpage being down?

this is exactly what it is, i attempted to fork and replace the urls the extention is trying to fetch with archive.org links but it seems most the pages have not been archived (see https://web.archive.org/web/20240000000000*/https://onepace.net/images/arcs/ or https://web.archive.org/web/20240000000000*/https://onepace.net/images/episodes/) unless someone saved these pages on a different archiving service we are kind of screwed till it comes back

**Comment by Charlielx** [comment] 2024-08-25 06:23
> > Same issue here. Might it have something to do with onepace webpage being down?
> 
> this is exactly what it is

I was so confused why I couldn't get mine to match after I had to reinstall Jellyfin when it had previously worked fine. This makes so much sense. Hopefully its back soon

**Comment by jwueller** [comment] 2024-08-30 10:40
Yeah, unfortunately the site is currently down and the metadata can't be pulled because of that. I'll think about how to mitigate something like this happening in the future.

It's indeed a duplicate, so I'll close this in favor of #66.

**Closed as completed by jwueller** 2024-08-30 10:40 UTC
Labels: duplicate
