### ISSUE TITLE
Plugin not creating season for 'Whiskey Peak' and 'Post-Enies Lobby'

### ISSUE THREAD

**Issue by maeveuay** [jwueller/jellyfin-plugin-onepace#34] opened 2023-09-23 22:42 UTC
Hello!

This plugin is working a treat other than two Arcs not being given their own Jellyfin 'Season'
Is there something wrong with my naming/folder scheme?
I got it from a One Pace Batch download, and they named it for Plex, so I renamed everything to the format you see in the images below.

Jellyfin:
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/108652136/8e6dc767-1071-4fd3-a92b-ba6b1998afcb)
File Structure:
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/108652136/81563b4e-babc-4020-ab1f-7796abea368a)
![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/108652136/c642ad8c-cf69-413b-b33a-9d7cee494836)

If you need any logs just lemme know :)

**Comment by sahus22** [comment] 2023-10-09 20:32
This is how I have my arcs arranged, and this is how One Pace arranges them too.
Guess the plugin is better at recognizing it this way.

 ![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/31122182/59324af4-2feb-45b3-bee7-93ecb742a25b)

**Comment by NunoMouraz** [comment] 2023-10-09 22:55
@maeveuay I believe the problem is due to the fact of how the plugin's arc search was made:

In the case of your path `D:\...\One Pace - Arc 18 - Post-Enies Lobby`:
- It will search for the API's manga chapters (e.g. "700-800") in each arc and see if they are present in your path (and if they match ofc). _In your case this step is skipped._
- It will search in the API's title of each arc and see if itself is contained anywhere within your path
- Since the _(as of today)_ Arc 19 titled Ennies Lobby is the **FIRST** arc on the list where its title "Ennies Lobby" is contained somewhere in your path "...Post-**Enies Lobby**...", it will stop the search there and identify the wrong arc, instead of the correct arc.

@maeveuay How to fix it yourself? Well, for example,  just add `431-441` aka (the manga chapters) somewhere in there, since it searches for that stuff first. Something like: `One Pace - Arc 20 - Post-Enies Lobby [431-441]`. Then rescan your library / metadata. _Maybe it will also work on the other chapter._

How should the plugin fix it?
IDK. Maybe try to the find the longest match or something 😊:
`ArcIdentifier.cs`
![solution](https://github.com/jwueller/jellyfin-plugin-onepace/assets/7382885/2a30bcab-52d7-4c79-873d-2e845dd57fac)

**Comment by maeveuay** [comment] 2023-10-13 02:32
Thank you!
The trick worked for Post-Enies, but not for Reverse Whiskey Arc.
Bit new to Github, should I close the issue?

**Comment by jwueller** [comment] 2024-01-04 20:19
Hi, sorry for not getting to this sooner.

First of all, thank you @NunoMouraz for taking this on! As they correctly identified, this is an issue with the matching logic in the plugin, which has now been fixed in version 1.4.0.0.

However, there is also a different issue in this case: The Arc is called "Whisky Peak", not "Whiskey Peak". This is such a common misspelling, that even the One Pace team has made this mistake in the past, particularly in release filenames. The new version also deals with this by accepting both spellings.

Hopefully that resolves all of your issues. Thanks for reporting them! Please feel free to reopen this if you are still observing weirdness with the matching.

**Closed by jwueller** 2024-01-04 20:19 UTC
